name: Build and Push Tasky App

on:
  push:
    branches: [main]
    paths:
      - app/tasky/Dockerfile
      - .github/workflows/docker-build.yml

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Tasky Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app/tasky
          file: ./app/tasky/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/rogmanster/wiz:latest
            ghcr.io/rogmanster/wiz:${{ github.sha }}

